# Generated by Django 4.1.2 on 2022-10-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='user_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
