# Generated by Django 4.1.2 on 2022-10-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser_app', '0002_alter_link_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='last_enter_date',
        ),
        migrations.RemoveField(
            model_name='link',
            name='unique_users_counter',
        ),
        migrations.CreateModel(
            name='RedirectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_user_ip', models.GenericIPAddressField()),
                ('enter_date', models.DateTimeField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_history', to='browser_app.link')),
            ],
        ),
    ]
