# Generated by Django 4.1.2 on 2022-11-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser_app', '0003_remove_link_last_enter_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirecthistory',
            name='country',
            field=models.TextField(default='Unknown'),
        ),
    ]
